name: Deploy React App
on: 
  push:
    branches:
      - master
    paths-ignore:
      - './github/workflows/*'
jobs:
  test_my_app_react:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test React App
        run: npm run test
  lint-work:
    runs-on: ubuntu-latest
    needs: test_my_app_react
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint Application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint-work
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build Application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
